
[SeccionApi]

# --- VIAJES ---
api_viajes_url_listar = http://localhost:8080/api/viajes/listar
api_viajes_url_crear = http://localhost:8080/api/viajes/crear
api_viajes_url_actualizar = http://localhost:8080/api/viajes/actualizar
api_viajes_url_eliminar   = http://localhost:8080/api/viajes/eliminar
api_viajes_url_por_id = http://localhost:8080/api/viajes

# --- VEHICULOS ---
api_vehiculos_url_listar = http://localhost:8080/api/vehiculos/listar
api_vehiculos_url_crear = http://localhost:8080/api/vehiculos/crear
api_vehiculos_url_actualizar = http://localhost:8080/api/vehiculos/actualizar
api_vehiculos_url_eliminar = http://localhost:8080/api/vehiculos/eliminar
api_vehiculos_url_por_id = http://localhost:8080/api/vehiculos

# --- USUARIOS ---
api_usuarios_url_listar = http://localhost:8080/api/usuarios/listar
api_usuarios_url_crear = http://localhost:8080/api/usuarios/crear
api_usuarios_url_actualizar = http://localhost:8080/api/usuarios/actualizar
api_usuarios_url_eliminar = http://localhost:8080/api/usuarios/eliminar
api_usuarios_url_por_id = http://localhost:8080/api/usuarios

# --- RESERVAS ---
api_reservas_url_listar = http://localhost:8080/api/reservas/listar
api_reservas_url_crear = http://localhost:8080/api/reservas/crear
api_reservas_url_actualizar = http://localhost:8080/api/reservas/actualizar
api_reservas_url_eliminar = http://localhost:8080/api/reservas/eliminar
api_reservas_url_por_id = http://localhost:8080/api/reservas