
[SeccionApi]

# --- VIAJES ---
api_viajes_url_listar = http://localhost:8080/api/viajes/listar
api_viajes_url_crear = http://localhost:8080/api/viajes/crear
api_viajes_url_actualizar = http://localhost:8080/api/viajes/actualizar
api_viajes_url_eliminar   = http://localhost:8080/api/viajes/eliminar
api_viajes_url_por_id = http://localhost:8080/api/viajes

# --- VEHICULOS ---
api_vehiculos_url_listar = http://localhost:8080/api/vehiculos/listar
api_vehiculos_url_crear = http://localhost:8080/api/vehiculos/crear
api_vehiculos_url_actualizar = http://localhost:8080/api/vehiculos/actualizar
api_vehiculos_url_eliminar = http://localhost:8080/api/vehiculos/eliminar
api_vehiculos_url_por_id = http://localhost:8080/api/vehiculos